In [33]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np

In [34]:
df=pd.read_csv('healthcare_dataset.csv')

In [35]:
df['Test Results'].value_counts()

Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64

In [36]:
df.head()

Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31   
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22   
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18   
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19   

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross   
1   Samantha Davies                     Kim Inc           Medicare   
2  Tiffany Mitchell                    Cook PLC              Aetna   
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare   
4    Kathleen Hanna                 White-White              Aetna   

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          328         Urgent     2024-02-02  Paracetamol   
1    33643.327287          265      Emergency     2019-08-26    Ibuprofen   
2    27955.096079          205      Emergency     2022-10-07      Aspirin   
3    37909.782410          450       Elective     2020-12-18    Ibuprofen   
4    14238.317814          458         Urgent     2022-10-09   Penicillin   

   Test Results  
0        Normal  
1  Inconclusive  
2        Normal  
3      Abnormal  
4      Abnormal

In [37]:
#Data Cleaning 

In [38]:

df['Test Results']=df['Test Results'].replace({'Inconclusive':0,'Normal':1,'Abnormal':2})
df.head()

/tmp/ipykernel_21210/3482288097.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Test Results']=df['Test Results'].replace({'Inconclusive':0,'Normal':1,'Abnormal':2})


Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31   
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22   
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18   
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19   

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross   
1   Samantha Davies                     Kim Inc           Medicare   
2  Tiffany Mitchell                    Cook PLC              Aetna   
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare   
4    Kathleen Hanna                 White-White              Aetna   

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          328         Urgent     2024-02-02  Paracetamol   
1    33643.327287          265      Emergency     2019-08-26    Ibuprofen   
2    27955.096079          205      Emergency     2022-10-07      Aspirin   
3    37909.782410          450       Elective     2020-12-18    Ibuprofen   
4    14238.317814          458         Urgent     2022-10-09   Penicillin   

   Test Results  
0             1  
1             0  
2             1  
3             2  
4             2

In [39]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [40]:
df['Medical Condition'].value_counts()
df['Medication'].value_counts()

Medication
Lipitor        11140
Ibuprofen      11127
Aspirin        11094
Paracetamol    11071
Penicillin     11068
Name: count, dtype: int64

In [41]:
# Encodeing  All Input Columns 

In [42]:
# Data Spliting 
x=df.drop(columns=['Test Results'])
y=df['Test Results']

In [43]:
# Feture Selection
x=x.drop(['Name','Date of Admission','Doctor','Discharge Date','Hospital'],axis=1)

In [44]:
# Splitting 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [45]:

# Now Encodeing label Encoder Menually 
x_train['Gender']=x_train['Gender'].replace({'Male':0,'Female':1})
x_test['Gender']=x_test['Gender'].replace({'Male':0,'Female':1})

#Label Encoder Apply in sklearn with Blood Type
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x_train['Blood Type']=le.fit_transform(x_train['Blood Type'])
x_test['Blood Type']=le.transform(x_test['Blood Type'])

# label Encoding in Insurance Provider
le=LabelEncoder()
x_train['Insurance Provider']=le.fit_transform(x_train['Insurance Provider'])
x_test['Insurance Provider']=le.transform(x_test['Insurance Provider'])

/tmp/ipykernel_21210/2862606866.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train['Gender']=x_train['Gender'].replace({'Male':0,'Female':1})
/tmp/ipykernel_21210/2862606866.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test['Gender']=x_test['Gender'].replace({'Male':0,'Female':1})


In [46]:
#Label Encoder Apply in sklearn with Blood Type
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x_train['Medical Condition']=le.fit_transform(x_train['Medical Condition'])
x_test['Medical Condition']=le.transform(x_test['Medical Condition'])

In [47]:
from sklearn.preprocessing import OrdinalEncoder

# Define the ordinal structure (from least to most urgent)
urgency_order = [['Elective', 'Urgent', 'Emergency']]

# Initialize the encoder with the defined order
encoder = OrdinalEncoder(categories=urgency_order,handle_unknown='use_encoded_value',unknown_value=-1)

# Fit the encoder ONLY on training data
encoder.fit(x_train[['Admission Type']])  # Double brackets for DataFrame input

# Transform both train and test data
x_train['Encoded_adtype'] = encoder.transform(x_train[['Admission Type']])
x_test['Encoded_adtype'] = encoder.transform(x_test[['Admission Type']])

# Drop the original column
x_train= x_train.drop('Admission Type', axis=1)
x_test= x_test.drop('Admission Type', axis=1)

In [48]:
# Medication lablel Encoder 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x_train['Medication']=le.fit_transform(x_train['Medication'])
x_test['Medication']=le.transform(x_test['Medication'])

# Data Scaleing 


In [49]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# নিউমেরিক কলাম নির্বাচন
numeric_cols = ['Age', 'Billing Amount', 'Room Number']

# স্কেলার ইনিশিয়ালাইজ
scaler = StandardScaler()

# শুধু ট্রেন ডেটায় ফিট করুন
scaler.fit(x_train[numeric_cols])

# ট্রেন এবং টেস্ট ডেটা স্কেল করুন
x_train[numeric_cols] = scaler.transform(x_train[numeric_cols])
x_test[numeric_cols] = scaler.transform(x_test[numeric_cols])

# এখন x_train এবং x_test-এ মূল কলামই স্কেল্ড ভ্যালু ধারণ করছে

# Traget Column Encodeing

# Model Apply 

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
# মডেল ইনিশিয়ালাইজ
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [52]:
y_pred=model.predict(x_test)

In [53]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# প্রেডিকশন
y_pred = model.predict(x_test)

# একুরেসি
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.9}")

# কনফিউশন ম্যাট্রিক্স
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ক্লাসিফিকেশন রিপোর্ট
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.334234234

Confusion Matrix:
[[1164 1294 1159]
 [1237 1348 1144]
 [1221 1335 1198]]

Classification Report:
              precision    recall  f1-score   support

           0       0.32      0.32      0.32      3617
           1       0.34      0.36      0.35      3729
           2       0.34      0.32      0.33      3754

    accuracy                           0.33     11100
   macro avg       0.33      0.33      0.33     11100
weighted avg       0.33      0.33      0.33     11100



In [54]:
y_pred

array([1, 0, 0, ..., 2, 0, 0])